### ISSUE TITLE
Make the landing page, clone of existing homepage.

### ISSUE THREAD

**Issue by Mark-Jung** [PerfDevTeam/perf_landing#1]
tryperf.com

**Comment by jameswhang** [comment]
Is cloning that site really the best thing to do? Not trying to stick my nose into everything but I don't think the current landing page looks particularly professional / meet standards of our target audience.

**Comment by jameswhang** [comment]
Thoughts? @myidsan

**Comment by myidsan** [comment]
Agreed. Our current landing page doesn't provide a 'call for action.' We need to rethink what we want the users to feel and do after coming to our page.
